# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventario_pb2 as inventario__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventario_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventarioStub:
    """Servicio de Inventario para gestión de productos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerProducto = channel.unary_unary(
                '/inventario.Inventario/ObtenerProducto',
                request_serializer=inventario__pb2.ProductoRequest.SerializeToString,
                response_deserializer=inventario__pb2.ProductoResponse.FromString,
                _registered_method=True)
        self.ListarProductos = channel.unary_unary(
                '/inventario.Inventario/ListarProductos',
                request_serializer=inventario__pb2.ListaRequest.SerializeToString,
                response_deserializer=inventario__pb2.ListaResponse.FromString,
                _registered_method=True)
        self.RegistrarProducto = channel.unary_unary(
                '/inventario.Inventario/RegistrarProducto',
                request_serializer=inventario__pb2.NuevoProductoRequest.SerializeToString,
                response_deserializer=inventario__pb2.ProductoResponse.FromString,
                _registered_method=True)


class InventarioServicer:
    """Servicio de Inventario para gestión de productos
    """

    def ObtenerProducto(self, request, context):
        """Obtiene un producto por su ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarProductos(self, request, context):
        """Lista todos los productos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistrarProducto(self, request, context):
        """Registra un nuevo producto
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventarioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerProducto,
                    request_deserializer=inventario__pb2.ProductoRequest.FromString,
                    response_serializer=inventario__pb2.ProductoResponse.SerializeToString,
            ),
            'ListarProductos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarProductos,
                    request_deserializer=inventario__pb2.ListaRequest.FromString,
                    response_serializer=inventario__pb2.ListaResponse.SerializeToString,
            ),
            'RegistrarProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarProducto,
                    request_deserializer=inventario__pb2.NuevoProductoRequest.FromString,
                    response_serializer=inventario__pb2.ProductoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventario.Inventario', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventario.Inventario', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inventario:
    """Servicio de Inventario para gestión de productos
    """

    @staticmethod
    def ObtenerProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.Inventario/ObtenerProducto',
            inventario__pb2.ProductoRequest.SerializeToString,
            inventario__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarProductos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.Inventario/ListarProductos',
            inventario__pb2.ListaRequest.SerializeToString,
            inventario__pb2.ListaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistrarProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.Inventario/RegistrarProducto',
            inventario__pb2.NuevoProductoRequest.SerializeToString,
            inventario__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
