# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventario.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inventario.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10inventario.proto\x12\ninventario\"E\n\x08Producto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x01\x12\r\n\x05stock\x18\x04 \x01(\x05\"\x1d\n\x0fProductoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"K\n\x10ProductoResponse\x12&\n\x08producto\x18\x01 \x01(\x0b\x32\x14.inventario.Producto\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"\x0e\n\x0cListaRequest\"G\n\rListaResponse\x12\'\n\tproductos\x18\x01 \x03(\x0b\x32\x14.inventario.Producto\x12\r\n\x05total\x18\x02 \x01(\x05\"E\n\x14NuevoProductoRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x0e\n\x06precio\x18\x02 \x01(\x01\x12\r\n\x05stock\x18\x03 \x01(\x05\x32\xf7\x01\n\nInventario\x12L\n\x0fObtenerProducto\x12\x1b.inventario.ProductoRequest\x1a\x1c.inventario.ProductoResponse\x12\x46\n\x0fListarProductos\x12\x18.inventario.ListaRequest\x1a\x19.inventario.ListaResponse\x12S\n\x11RegistrarProducto\x12 .inventario.NuevoProductoRequest\x1a\x1c.inventario.ProductoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTO']._serialized_start=32
  _globals['_PRODUCTO']._serialized_end=101
  _globals['_PRODUCTOREQUEST']._serialized_start=103
  _globals['_PRODUCTOREQUEST']._serialized_end=132
  _globals['_PRODUCTORESPONSE']._serialized_start=134
  _globals['_PRODUCTORESPONSE']._serialized_end=209
  _globals['_LISTAREQUEST']._serialized_start=211
  _globals['_LISTAREQUEST']._serialized_end=225
  _globals['_LISTARESPONSE']._serialized_start=227
  _globals['_LISTARESPONSE']._serialized_end=298
  _globals['_NUEVOPRODUCTOREQUEST']._serialized_start=300
  _globals['_NUEVOPRODUCTOREQUEST']._serialized_end=369
  _globals['_INVENTARIO']._serialized_start=372
  _globals['_INVENTARIO']._serialized_end=619
# @@protoc_insertion_point(module_scope)
